### PR TITLE
+ Run as systemd unit installation manual

### PR DESCRIPTION
**Pull request by m0zgen**

### CODE REVIEW

**Comment by 0xERR0R** [comment]
Hey,
thank you for your work! :+1:  I like the idea to provide the installation guide with systemd service, but I would like to keep it outside of this repo. The reason is: I can't maintain all possible installation kinds for blocky. There are some other projects outside, made and maintained by other awesome people (like [Helm Chart](https://artifacthub.io/packages/helm/k8s-at-home/blocky/4.0.0), [AUR Package for Arch](https://aur.archlinux.org/packages/blocky/) or [Apline package](https://pkgs.alpinelinux.org/package/edge/testing/x86/blocky)).

My suggestion: we can take your description in installation.md, you create your own repo with other installation scripts for centos, description etc. We link your repo in installation.md. What do you think?

**Comment by m0zgen** [comment]
P.S.

Today I'm using blocky with my free projecte, and I wrote additional code to automation installs - Blocky, Prometheus, Grafana, Nginx as DoH front and I'll plan write additional service for regex blok/white lists converting to plain text lists.

Thanks fo you work, Blocky os the best solution for me. If I'll complete my Blocky automation deployment routines, I'll be grateful for will review and evaluation of my work. thanks in advance)

Have a nice day!;)

**Comment by m0zgen** [comment]
Hey, I created new repo with name `blocky-installer`. This installer tested and worked on CentOS. After installation Blocky works as `systemd` service.

### Features

* Steb-by-step / Automate installer
* Detect and download latest `blocky` release from official repo
* Install Blocky under simple user
* Reinstall `blocky` (with backup)
* Blocky is installed as systemctl unit service to `/opt/blocky` catalog as default
* After install Blocky works from regular user
* Install additional software (optionally):
  * Cloudflared
  * Cerbot
  * Nginx
  * Prometheus Stack

### Links

* [blocky-installer](https://github.com/m0zgen/blocky-installer.git)
* [prometheus-stack-installer](https://github.com/m0zgen/prometheus-stack-installer.git)

**Comment by 0xERR0R** [comment]
Thank you for your work! I added the link to your repo here: https://0xerr0r.github.io/blocky/installation/#installation-script-for-centosfedora.

I think, we can close this PR without merging, all relevant information (such as Systemd unit file etc) is covered by your installer. Right?

**Comment by m0zgen** [comment]
Right. Thank you!)

**Pull request closed without merging**
