### PR TITLE
Add support for SRV and TXT in custom DNS zones

### LINKED ISSUE #1587: Support for additional record types in `customDNS.zone`
I'm running an internal CalDAV server and exposing its DNS records via Blocky, but ideally this would include a pair of `SRV` and `TXT` records and Blocky doesn't support either.

For reference, the records would look like this:

```
$ORIGIN example.com.
_caldavs._tcp	IN	SRV	0 5 443 cal.example.com.
_caldavs._tcp	IN	TXT	"path=/"
_carddavs._tcp	IN	SRV	0 5 443 cal.example.com.
_carddavs._tcp	IN	TXT	"path=/"
```

### PR DESCRIPTION
**Pull request by Terrance**
Fixes #1587.

I wonder if there's a better way to do this more generically, but for now I've just added SRV and TXT explicitly, tests included.

### CODE REVIEW

**Comment by kwitsch** [comment]
Thanks for the contribution. 👍

If you fix the failing workflows I'll merge it.

**Comment by Terrance** [comment]
Ah, I saw the option to format but not lint as it wasn't set up as a VSCode build task.  Should hopefully be happy now.

**Comment by kwitsch** [comment]
> Ah, I saw the option to format but not lint as it wasn't set up as a VSCode build task.  Should hopefully be happy now.

I forgot to add it, sorry about that. 🫣

**Review by kwitsch — APPROVED** [review]
👍

**Pull request merged**
