### PR TITLE
Use same minimum TLS version & cipher for DoH server as DoT server

### LINKED ISSUE #517: Unify the minimum TLS version of DoH and DoT
Currently, TLS 1.0 and TLS 1.1 is not offered by blocky's DoT implementation, but offered by blocky's DoH implementation.

As DoH and DoT are both still something new, and there're security concerns about TLS < 1.2, maybe should unify both of their minimum TLS version to v1.2 here?

Using testssl.sh(https://github.com/drwetter/testssl.sh) to test the TLS version.

On https port:
```
 Testing protocols via sockets except NPN+ALPN 

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      offered (deprecated)
 TLS 1.1    offered (deprecated)
 TLS 1.2    offered (OK)
 TLS 1.3    offered (OK): final
 NPN/SPDY   not offered
 ALPN/HTTP2 h2, http/1.1 (offered)
```

On TLS port:
```
 Testing protocols via sockets except NPN+ALPN 

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      not offered
 TLS 1.1    not offered
 TLS 1.2    offered (OK)
 TLS 1.3    offered (OK): final
 NPN/SPDY   not offered
 ALPN/HTTP2 not offered

```

### PR DESCRIPTION
**Pull request by PeterDaveHello**
This is a #520 follow-up PR. Also fixes #517.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I checked the other tests, looks like simple function here might not really need those tests? Hope it's right 😅

**Comment by PeterDaveHello** [comment]
An interesting thing is that `redis/redis.go` is impacted?


[Impacted Files](https://codecov.io/gh/0xERR0R/blocky/pull/524?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Dimitri+Herzog) | Coverage Δ |  
-- | -- | --
[server/server.go](https://codecov.io/gh/0xERR0R/blocky/pull/524/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Dimitri+Herzog#diff-c2VydmVyL3NlcnZlci5nbw==) | 85.81% <94.11%> (+0.42%) | ⬆️
[redis/redis.go](https://codecov.io/gh/0xERR0R/blocky/pull/524/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Dimitri+Herzog#diff-cmVkaXMvcmVkaXMuZ28=) | 66.44% <0.00%> (-24.35%) | ⬇️

**Comment by 0xERR0R** [comment]
This coverage calculation is not always accurate.

**Comment by 0xERR0R** [comment]
It looks good, thank you!

**Pull request merged**
