### PR TITLE
Add cd bit to cache key to fix DNS poisoning

### LINKED ISSUE #455: DNS cache poison of DNSSEC?
By default, if the upstream resolver is doing DNSSEC validation, the query of the record with broken signature will return [SERVFAIL](https://dnssec.vs.uni-due.de/dig-sigfail), but using `dig` with the `+cd` flag(_to set the CD (checking disabled) bit in the query_) to query domain will ask the resolver to bypass the DNSSEC check, return the result without validation.

Just noticed that the result of a CD bit enabled query will be cached by blocky, and then served to the client no matter if they enabled the CD bit, once the cache is created, the following query without CD bit will retrieve the same result without DNSSEC validation as the CD bit enabled.

The test result using [Quad9](https://quad9.net/):

```
$ dig +short sigfail.verteiltesysteme.net @9.9.9.9
$ dig +short sigfail.verteiltesysteme.net @9.9.9.9
$ dig +cd +short sigfail.verteiltesysteme.net @9.9.9.9
134.91.78.139
$ dig +short sigfail.verteiltesysteme.net @9.9.9.9
```

The test result using Block to proxy queries to Quad9 via DoH:

```
$ dig +short sigfail.verteiltesysteme.net @::1
$ dig +short sigfail.verteiltesysteme.net @::1
$ dig +cd +short sigfail.verteiltesysteme.net @::1
134.91.78.139
$ dig +short sigfail.verteiltesysteme.net @::1
134.91.78.139
```

Not sure if this is something should be fixed? Thanks.

### PR DESCRIPTION
**Pull request by ThinkChaos**
The CheckingDisabled flag tells the resolver to skip DNSSEC signature
verification.

Fixes #455

### CODE REVIEW

**Comment by ThinkChaos** [comment]
Also relates to #471.

I think before merging we should determine if there are other fields missing from the key.
One thing that comes to mind but I haven't checked is that we might cache truncated responses.

**Comment by 0xERR0R** [comment]
Hey, thanks for your PR! I skimmed over the code: the usage of the CD bit in the cache key will potentially increase the number of cached entries if some of the clients use CD and some not (maybe this is only a theoretical problem). My idea for the solution (not tired yet, maybe this can't work this way) was:
The cache key remain. We have the complete DNS response in the cache and we can determine if the response is valid (EDNS/OPT section). On new request, we check if CD flag is set, if yes, we return the cached item (valid or invalid). If not, we check if cached item is valid and return it only if it is.
As I mentioned, I didn't check this approach, but if it works, we can keep the cache size. The only change is, we "mark" invalid cache entries as "bad data" and return this data only if explicitly desired.

What do you think about it?

**Comment by ThinkChaos** [comment]
I did this change as a quick way to fix the DNS poisoning issue, but indeed there's more work to be done.
As you said, this causes duplication for responses that are DNSSEC valid since the CD flag doesn't impact the result in that case we should use a single cache entry for both. I think your approach sounds good for that.

I also think we first need to go over the RFCs and determine what other changes we need to make, and probably other stub resolver code, to have a complete picture of what special care is needed before making bigger changes.

For instance, the DO flag tells resolvers they should include `RRSIG`s, and if space is an issue, set TC (truncate) in the response. Blocky doesn't take into account if DO is set when using the cache. That's why I was seeing `RRSIG`s in responses from blocky even if I wasn't using DNSSEC (testing with dig).
In the case of DO, it's possible to use the same entry whether the flag is set or not, as long as you strip the `RRSIG`s when it is not.
RFC4035 has [a section](https://www.ietf.org/rfc/rfc4035.html#section-4.9) on how stub resolvers should interact with DNSSEC related flags.

Later I'll start by working on #464  and then will do some more reading related to this.
Do you want to open a new issue, or maybe expand the scope of #455 to include the other changes we need to make to caching, including determining exactly what they are?

**Comment by 0xERR0R** [comment]
Yes, you're right, blocky doesn't care actually about request flags and simple caches responses. This will work for the most cases, but it should be fixed.
Regarding the scope expansion or creating of new issue - please feel free to do as it fits best.

**Comment by PeterDaveHello** [comment]
Not sure if considering the AD (authentic data) bit in the implementation will help?

**Comment by PeterDaveHello** [comment]
Should keep it opened.

**Pull request closed without merging**
