### PR TITLE
fix: add timezone data to docker container

### LINKED ISSUE #740: Timezone ignored in docker container
Timezone (set as env variable TZ) is ignored in development tag:

Current localtime (Europe/Berlin): 11:24

Test with development -> shows UTC:

```sh
docker run --rm -e TZ=Europe/Berlin spx01/blocky:development
[2022-11-10 10:24:29]  INFO _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
```

Test with v0.19 -> shows local time

```sh
docker run --rm -e TZ=Europe/Berlin spx01/blocky:v0.19
[2022-11-10 11:25:37]  INFO _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
```

### PR DESCRIPTION
**Pull request by 0xERR0R**
closes #740

### CODE REVIEW

**Comment by kwitsch** [comment]
This change won't work as it just duplicates the zone database.
The zonedata is already included in the static build.

A possible fix would be an init function in main_static.go which reads the TZ environment variable and sets the localtime with the help of the embedded zonedatabase.

**Review by kwitsch — CHANGES_REQUESTED** [review]
This change won't work as it just duplicates the zone database.
The zonedata is already included in the static build.

A possible fix would be an init function in main_static.go which reads the TZ environment variable and sets the localtime with the help of the embedded zonedatabase.

**Comment by kwitsch** [comment]
Currently unable to test but this should fix the problem if added to the init function of main_static.go:

```
  if tz := os.Getenv("TZ"); tz != "" {
      var err error
      time.Local, err = time.LoadLocation(tz)
      if err != nil {
         log.Printf("error loading location '%s': %v\n", tz, err)
      }
   }
```

**Comment by kwitsch** [comment]
Interesting wouldn't expect that 😅

If you like the APK approach better we should at least remove the native time/tzdata package to reduce image size.
Alternatively there is an approach in the source link which uses the zone info zip file of go.

**Comment by 0xERR0R** [comment]
What do you mean with "remove the native time/tzdata package"? There is no tzdata files in the scratch image. I'm not sure if its the best solution to install the tzdata package, but it is common practice.

**Comment by kwitsch** [comment]
The [time/tzdata](https://github.com/0xERR0R/blocky/blob/development/main_static.go#L7) contains the tzdata information as a native golang package.

Sorry for the missunderstanding 😅

Blocky should still work if you remove it because you currently copy the files from the apk installation.

**Comment by 0xERR0R** [comment]
ok, got it. I removed the tzdata from image. It makes sense to use it from golang and save the image size. 👍

**Review by kwitsch — APPROVED** [review]
Unable to test it at the moment but looks correct code wise. 👍

**Pull request merged**
