### PR TITLE
Helm Chart: KaH -> TrueCharts and add TrueNAS SCALE Native App

### PR DESCRIPTION
**Pull request by Ornias1993**
# Background

- The k8s-at-home project has deprecated all it's helm charts, including blocky.
- We, as TrueCharts, cover most of the applications previously covered by k8s-at-home (and a lot more)
- We've, as TrueCharts, decided to invest heavily into blocky as our adviced go-to solutions for all cases of "DNS-Enhancement" and filtering
- We've integrated k8s_gateway to allow for easy split-DNS (local-external) setup on kubernetes.
- We've rebuild a Helm Chart from scratch, which includes support for 2 different styles of entering any Blocky config directly into `values.yaml`
- We've also designed a complete GUI for TrueNAS SCALE based on the same helm chart

# PR

Hence we would request/suggest:
- The helm-chart URL to be changed to ours (as there is no support/updates over at k8s-at-home)
- The SCALE App also being added in the list of, downstream, supported platforms

### CODE REVIEW

**Comment by Ornias1993** [comment]
Blocked waiting for merging of https://github.com/truecharts/charts/pull/3875

**Comment by kwitsch** [comment]
> Blocked waiting for merging of [truecharts/charts#3875](https://github.com/truecharts/charts/pull/3875)

Mentioned merge request is merged at 25.09.22

**Comment by Ornias1993** [comment]
Still waiting for doing some past deployment tests and verifying the docs once deployed on the website…

**Comment by Ornias1993** [comment]
Ready now:
- Verified for basic functionality (resolving things, whitelisting, blocklisting, upstreams)
- Verified for k8s_gateway integration
- Verified default configuration to be useable "out of the box"
- Improved documentation

Needs additional work:
- DoT and DoH on TrueNAS SCALE, due to GUI and Ingress complications inherent to that platform (should be useable on native helm though)
- Document some example configurations for new users

Verified to be not-working:
- Integrated blocky-GUI, due to upstream bug. Should become functional the second the bug is fixed

**Pull request merged**
