### PR TITLE
Fix the indent of yaml code block in docs/configuration.md

### PR DESCRIPTION
**Pull request by PeterDaveHello**
There's something wrong with the old one, there are inconsistent and broken indent in it 😅

### CODE REVIEW

**Comment by 0xERR0R** [comment]
Good catch :+1: 
I had problems in the past with auto formatting on save in Goland: it has periodically broke yaml formatting inside the MD file. I thought, I fixed it. :no_good:

**Comment by PeterDaveHello** [comment]
@0xERR0R thanks! BTW, does https://github.com/0xERR0R/blocky/tree/gh-pages need a manual build to update its content?

**Comment by 0xERR0R** [comment]
It will be updated on master commit or when development branch will be merged on master. I merge usually just before new release, because documentation can contain description of new parameters (future release).

**Comment by 0xERR0R** [comment]
I think, I'll cherry pick your commit to update the doc page.

**Comment by PeterDaveHello** [comment]
No rush 👍

**Pull request merged**
