### PR TITLE
Hide DoH client http header "User-Agent"

### LINKED ISSUE #446: Hide http user agent for DNS over HTTPS like what Firefox and iOS do?
Just found that currently blocky is using the default HTTP user agent string: `Go-http-client/1.1`, though we know that there're tons of user profiling mechanisms to find out the tools and details about the users, but maybe it'll be great if we can give one less information, like user agent string? That's what Firefox and iOS doing, both known as privacy protected products, is this something blocky would like to do 😃

### PR DESCRIPTION
**Pull request by PeterDaveHello**
I'm newbie to Go, please help verify the patch, thanks!

close #446

### CODE REVIEW

**Comment by 0xERR0R** [comment]
Thanks for your work! Your code change looks good, we can merge it. One question: your implementation sets empty string as user agent. The proposed solution (see https://github.com/0xERR0R/blocky/issues/446#issuecomment-1054665140) on #446 was to make the user-agent string configurable via config.yaml. It is absolutely ok for me to take your approach, I just want to avoid some misunderstandings. Do you think, it makes not really sense to make user-agent configurable?

**Comment by 0xERR0R** [comment]
closes #446

**Comment by PeterDaveHello** [comment]
@0xERR0R set it to empty looks good enough to me, configurable seems to be another level nice to have feature. Just I'm new to Golang, so make it configurable will be much more complex to me to finish it at this moment. Maybe we can do it later in the future. Or anyone who'd like to make the patch, well also be great.

**Comment by FileGo** [comment]
@PeterDaveHello Should be a fairly easy fix, but if you are too busy, let me know and I can do the configuration bit.

**Comment by 0xERR0R** [comment]
> @0xERR0R set it to empty looks good enough to me, configurable seems to be another level nice to have feature. Just I'm new to Golang, so make it configurable will be much more complex to me to finish it at this moment. Maybe we can do it later in the future. Or anyone who'd like to make the patch, well also be great.

ok, got it, thanks!

**Comment by 0xERR0R** [comment]
> @PeterDaveHello Should be a fairly easy fix, but if you are too busy, let me know and I can do the configuration bit.

@FileGo I'll merge the fix from @PeterDaveHello, if you are interested in making the user-agent header configurable -> your contributions are always welcome 🤝

**Comment by FileGo** [comment]
Yeah, might do it later today.

**Pull request merged**
