### PR TITLE
Do not run docker build on fork

### LINKED ISSUE #401: Development docker build fails on fork
I've got this repo forked and the development docker build GitHub action always fails on forked repo with every push, as it can't login to Docker Hub.

Perhaps it could be worth adding something to the likes of condition below, to prevent Docker build from running on forks?

```
if: github.repository == ‘0xERR0R/blocky’
```

### PR DESCRIPTION
**Pull request by FileGo**
Fixes #401.

### CODE REVIEW

**Comment by 0xERR0R** [comment]
Do we have the same problem with "Upload results to codecov" step?

**Comment by FileGo** [comment]
> Do we have the same problem with "Upload results to codecov" step?

It works fine, but not sure if that's the desired behaviour? Is there any benefit in codecov upload running on forks?

**Comment by 0xERR0R** [comment]
I was just wondering, why this PR has changed the code coverage. I think, this step can run on forks, but codecov should not consider any results from fork build. Not sure, how it currently works 🤷

**Comment by FileGo** [comment]
Yeah, not sure either really, it's only one line in a GH yaml 😐

**Pull request merged**
