### PR TITLE
Support for multiple configuration files

### PR DESCRIPTION
**Pull request by FileGo**
This adds support for multiple configuration files (in a single directory), as proposed in #512.

### CODE REVIEW

**Comment by FileGo** [comment]
Interesting, test fails on something that hasn't been changed.

@0xERR0R Any ideas?

**Comment by 0xERR0R** [comment]
> Interesting, test fails on something that hasn't been changed.
> 
> @0xERR0R Any ideas?

Is a flaky test which I can't reproduce locally ;(

**Comment by 0xERR0R** [comment]
Thanks for your work! If I understand your idea right, splitted files should contain distinct part of the target YAML. I mean, basically, all YAMLs in the directory will be concatenated together to a big target file. That means, there is no logical "merge" with attribute overwrite between pieces, right?

So following would (probably?) fail:
config1.yaml
```yaml
upstream:
  default:
    - 5.9.164.112
    - 1.1.1.1
```

config2.yaml
```yaml
upstream:
  someclient:
    - 1.2.3.4
```

I think, it can be a useful use case to separate config files per client or to split the blacklist configuration, but it could be technically difficult to merge the parts correct together (we have nested maps of maps in the config). What do you think?
 
Maybe we can leave it (take your implementation) but improve the documentation, so that it becomes clear that all config parts should have no overlapping. In this case it doesn't matter if the files are read in the alphabetically order or not.

**Comment by FileGo** [comment]
Exactly, current functionality assumes no parts of config will overlap and as you point out, it will fail the YAML unmarshal, if it does overlap.

I'll amend the documentation, to make it more clear.

**Comment by yunwu-jnpr** [comment]
I think it would be better to support `include` directive than blindly merging files under a directory.
You have much more control.

**Pull request merged**
