### PR TITLE
chore: update Golang 1.19

### PR DESCRIPTION
**Pull request by soulteary**

### CODE REVIEW

**Review by 0xERR0R — APPROVED** [review]
Looks good, thank you!

**Comment by 0xERR0R** [comment]
Go 1.19 was just released, golangci-lint job fails currently. Maybe they need some time to support 1.19. I found this issue: https://github.com/golangci/golangci-lint/issues/2922

**Comment by rhcarvalho** [comment]
Hi! Have a look at https://github.com/golangci/golangci-lint-action/issues/442#issuecomment-1203786890, maybe building golangci-lint from source is an option for you.

**Comment by soulteary** [comment]
Time flies so fast, I don't know what else is needed for this PR? @0xERR0R

**Comment by 0xERR0R** [comment]
Your PR is just fine. I'm waiting for golang 1.19 support in golangci-lint

**Pull request merged**
